services:
  - type: web
    name: anytime-contest-backend
    env: python
    plan: starter
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      # Storage backend selection (supabase, sheets, postgres, memory)
      - key: STORAGE_BACKEND
        value: supabase
      # Supabase configuration (recommended)
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      # Google Sheets configuration (fallback)
      - key: GOOGLE_SHEETS_API_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_SHEET_RANGE
        value: "Sheet1!A:E"
      # PostgreSQL configuration (legacy)
      - key: DATABASE_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      # CORS configuration
      - key: FRONTEND_ORIGINS
        value: "https://allow-git-main-anytimes-projects-166cfa49.vercel.app,https://allow-o3dttaag3-anytimes-projects-166cfa49.vercel.app,https://allow-khaki.vercel.app"
      - key: CORS_ALLOW_ORIGIN_REGEX
        value: "https://.*\\.vercel\\.app"
      - key: DB_POOL_MAX_SIZE
        value: "20"

